test_that('Test API', {
  req <- dataRequest('lmr', '615')
  expect_s4_class(req, 'dataRequestLMR')
  expect_vector(filters(req))
  req <- filterAge(req, filter='item', value='TOTALT')
  expect_s4_class(req, 'dataRequestLMR')
  req <- filterAge(req, filter='item', value=5)
  expect_s4_class(req, 'dataRequestLMR')
  req <- filterATC(req, filter='all', value='A01AA*')
  expect_s4_class(req, 'dataRequestLMR')
})
